# Generated by Django 4.0.2 on 2022-05-23 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choice_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaselineSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('visits', models.FloatField()),
            ],
        ),
    ]
