# Generated by Django 4.0.2 on 2022-03-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedsite',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifiedsite',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
