# Generated by Django 4.0.2 on 2022-05-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choice_model', '0004_alter_baselinesite_baseline_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
