# Generated by Django 4.0.2 on 2022-05-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice_model', '0007_baselinemodel_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedsite',
            old_name='_id',
            new_name='id',
        ),
    ]
