# Generated by Django 4.0.2 on 2022-05-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice_model', '0008_rename__id_modifiedsite_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedsite',
            old_name='bundle_id',
            new_name='bundle',
        ),
        migrations.RenameField(
            model_name='modifiedsitesbundle',
            old_name='history_id',
            new_name='user',
        ),
    ]
