# Generated by Django 4.0.2 on 2022-05-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice_model', '0009_rename_bundle_id_modifiedsite_bundle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiedsitesbundle',
            old_name='bundle_id',
            new_name='id',
        ),
    ]
