# Generated by Django 4.0.2 on 2022-08-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
